---
apiVersion: v1
kind: Secret
metadata:
  name: ryanj-thursday-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23DevLab/ryanj-thursday-gateway-gitops
